[build]
  # Directory to change to before starting a build
  base = "amrutam-ai"
  
  # Directory that contains the deploy-ready HTML files and assets
  publish = "out"
  
  # Default build command
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20.11.0"

# Redirect rules for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
